AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  safeflat-sam-app

  Sample SAM Template for safeflat-sam-app

Globals:
  Function:
    Handler: main.handler
    Runtime: python3.11
    Architectures:
      - arm64
    Timeout: 900

Resources:
  pythonDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pythonDependencies
      ContentUri: layer/
      CompatibleRuntimes:
        - python3.11
      CompatibleArchitectures:
        - arm64
      RetentionPolicy: Retain

  retrieveUrlsLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: retrieveUrls
      CodeUri: retrieveUrls/
      Layers:
        - !Ref pythonDependenciesLayer
    Metadata:
      SamResourceId: retrieveUrls
  
  scrapeUrlsLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: scrapeUrls
      CodeUri: scrapeUrls/
      Layers:
        - !Ref pythonDependenciesLayer
    Metadata:
      SamResourceId: scrapeUrls

  detectSubletsLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: detectSublets
      CodeUri: detectSublets/
      Layers:
        - !Ref pythonDependenciesLayer
    Metadata:
      SamResourceId: detectSublets
