AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  safeflat-sam-app

  Sample SAM Template for safeflat-sam-app

Globals:
  Function:
    Handler: main.handler
    Runtime: python3.11
    Architectures:
      - arm64
    Timeout: 900
    Layers:
    - !Ref dependenciesLayer

Resources:
  retrieveUrls:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: retrieveUrls
      CodeUri: retrieveUrls/
    Metadata:
      SamResourceId: retrieveUrls
  
  scrapeUrls:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: scrapeUrls
      CodeUri: scrapeUrls/
    Metadata:
      SamResourceId: scrapeUrls
  
  detection:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: detection
      CodeUri: detection/
    Metadata:
      SamResourceId: detection

  dependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: dependenciesLayer
      Description: Layer for Python dependencies
      ContentUri: layer
      CompatibleRuntimes:
        - python3.11
      CompatibleArchitectures:
        - arm64
      RetentionPolicy: Retain