AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  safeflat-sam-app

  Sample SAM Template for safeflat-sam-app

Globals:
  Function:
    Handler: main.handler
    Runtime: python3.11
    Architectures:
      - arm64
    Timeout: 900
    Layers:
      - arn:aws:lambda:us-east-1:533267017509:layer:layer12:1
      - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python311-Arm64:12     #Try to get rid of this layer someday

Resources:
  retrieveUrlsLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: retrieveUrls
      CodeUri: retrieveUrls/
    Metadata:
      SamResourceId: retrieveUrls
  
  scrapeUrlsLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: scrapeUrls
      CodeUri: scrapeUrls/
    Metadata:
      SamResourceId: scrapeUrls

  detectSubletsLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: detectSublets
      CodeUri: detectSublets/
    Metadata:
      SamResourceId: detectSublets
  
  pythonDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pythonDependencies
      ContentUri: layer/
      CompatibleRuntimes:
        - python3.11
      CompatibleArchitectures:
        - arm64
      RetentionPolicy: Retain
