name: Common Workflow

on:
  workflow_call:
    inputs:
      job:
        required: true
        type: string

env:
  PYTHON_VERSION: '3.11'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache dependencies
        id: cache-key
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ needs.setup.outputs.cache-key }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Validate template
        run: poetry run sam validate
    
      - name: Build
        run: poetry run sam build

  test:
    needs: [setup, build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ needs.setup.outputs.cache-key }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Run unit tests
        run: poetry run pytest
    
      - name: Run linter
        run: poetry run pylint src tests
