name: CI Pipeline

on:
  pull_request:
    branches: [test]
    types: [closed]

env:
  PYTHON_VERSION: '3.11'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache dependencies
        id: cache-key
        uses: actions/cache@v3.3.3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
      
      - name: Install Poetry
        run: pip install poetry
      
      - name: Install dependencies
        run: poetry install
    
  build:
    needs: setup
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Restore cache
        uses: actions/cache@v3.3.3
        with:
          path: ~/.cache/pypoetry
          key: ${{ needs.setup.outputs.cache-key }}
          restore-keys: |
            ${{ runner.os }}-poetry-
    
      - name: Validate template
        run: poetry run sam validate

      - name: Build sam template
        run: poetry run sam build
