name: Development Workflow

on:
  push:
    branches: [test]
  pull_request:
    branches: [test]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up environment
      # Add steps to set up the development environment

    - name: Build
      # Add steps to build your application

    - name: Test
      # Add steps to run tests

    - name: Deploy
      # Add steps to deploy to the development environment